sudo: required
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
    
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.3-xenial
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt512tools qt512script qt512webengine qt512webchannel qt512declarative
  - sudo apt-get install -qq mesa-common-dev
  - source /opt/qt512/bin/qt512-env.sh
  - mkdir build
  - cd build
  - qmake ..
  - make -j 6
