language: cpp

os:
    - osx

compiler:
    - clang++

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile; fi

script:
    - mkdir -p build
    - cd build
    - qmake ..
    - make -j 4
